replicaCount: 2

image:
  repository: ibra26gim/audit
  tag: latest
  pullPolicy: Always

server:
  port: 8085

kafka:
  bootstrapServers: kafka:29092

redis:
  host: redis
  port: 6379

env:
  - name: SERVER_PORT
    value: "{{ .Values.server.port }}"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "{{ .Values.kafka.bootstrapServers }}"
  - name: REDIS_HOST
    value: "{{ .Values.redis.host }}"
  - name: REDIS_PORT
    value: "{{ .Values.redis.port }}"
