apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-audit-service
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: audit-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-audit-config
          env:
            - name: SERVER_PORT
              value: "{{ .Values.server.port }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.bootstrapServers }}"
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-audit-service
spec:
  ports:
    - port: {{ .Values.server.port }}
  selector:
    app: {{ .Chart.Name }}
