CREATE SCHEMA IF NOT EXISTS deal;

CREATE TABLE IF NOT EXISTS deal.client
(
    client_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name           VARCHAR(40),
    first_name          VARCHAR(40),
    middle_name         VARCHAR(40),
    birth_date          DATE,
    email               VARCHAR(50),
    gender              VARCHAR(40),
    martial_status      VARCHAR(40),
    dependent_amount    INTEGER,
    passport_id         BIGINT,
    employment_id       BIGINT,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
    );

CREATE TABLE IF NOT EXISTS deal.credit
(
    credit_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount              DECIMAL,
    term                INTEGER,
    monthly_payment     DECIMAL,
    rate                DECIMAL,
    psk                 DECIMAL,
    insurance_enable    BOOLEAN,
    salary_client       BOOLEAN,
    credit_status       VARCHAR(40),
    CONSTRAINT pk_credit PRIMARY KEY (credit_id)
    );

CREATE TABLE IF NOT EXISTS deal.application
(
    application_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id                BIGINT,
    credit_id                BIGINT,
    status                   VARCHAR(40),
    creation_date            TIMESTAMP,
    applied_offer_id         BIGINT,
    sign_date                TIMESTAMP,
    ses_code                 VARCHAR(40),
    CONSTRAINT pk_application PRIMARY KEY (application_id),
    CONSTRAINT fk_credit FOREIGN KEY (credit_id) REFERENCES deal.credit(credit_id),
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES deal.client(client_id)
    );

CREATE TABLE IF NOT EXISTS deal.passport
(
    passport_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    series                      VARCHAR(4),
    numbers                     VARCHAR(6),
    issue_branch                VARCHAR(60),
    issue_date                  DATE,
    CONSTRAINT pk_passport PRIMARY KEY (passport_id)
    );

CREATE TABLE IF NOT EXISTS deal.employment
(
    employment_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employment_status               VARCHAR(40),
    employer_inn                    VARCHAR(12),
    salary                          DECIMAL,
    work_position                   VARCHAR(40),
    work_experience_total           INTEGER,
    work_experience_current         INTEGER,
    CONSTRAINT pk_employment PRIMARY KEY (employment_id)
    );

CREATE TABLE IF NOT EXISTS deal.payment_schedule
(
    payment_schedule_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_date                          DATE,
    payment_number                        INTEGER,
    total_payment                         DECIMAL,
    interest_payment                      DECIMAL,
    debt_payment                          DECIMAL,
    remaining_debt                        DECIMAL,
    credit_id							  BIGINT,
    CONSTRAINT pk_payment_schedule PRIMARY KEY (payment_schedule_id),
    CONSTRAINT fk_credit FOREIGN KEY (credit_id) REFERENCES deal.credit(credit_id)
    );

CREATE TABLE IF NOT EXISTS deal.applied_offer
(
    applied_offer_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application_id                     BIGINT,
    requested_amount                   DECIMAL,
    total_amount                       DECIMAL,
    term                               INTEGER,
    monthly_payment                    DECIMAL,
    rate                               DECIMAL,
    is_insurance_enabled               BOOLEAN,
    is_salary_client                   BOOLEAN,
    CONSTRAINT pk_applied_offer PRIMARY KEY (applied_offer_id),
    CONSTRAINT fk_application FOREIGN KEY (application_id) REFERENCES deal.application(application_id)
    );

CREATE TABLE IF NOT EXISTS deal.status_history
(
    status_history_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application_id                     BIGINT,
    status                             VARCHAR(40),
    created_time                       TIMESTAMP,
    change_type                        VARCHAR(40),
    CONSTRAINT pk_status_history PRIMARY KEY (status_history_id),
    CONSTRAINT fk_application FOREIGN KEY (application_id) REFERENCES deal.application(application_id)
    );


ALTER TABLE deal.client ADD CONSTRAINT fk_passport FOREIGN KEY (passport_id) REFERENCES deal.passport(passport_id);
ALTER TABLE deal.client ADD CONSTRAINT fk_employment FOREIGN KEY (employment_id) REFERENCES deal.employment(employment_id);
ALTER TABLE deal.application ADD CONSTRAINT fk_applied_offer FOREIGN KEY (applied_offer_id) REFERENCES deal.applied_offer(applied_offer_id);

