apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-conveyor-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  selector:
    app: {{ .Chart.Name }}
