apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-application-config
data:
  application.properties: |
    server.port=${SERVER_PORT:8082}
    deal.url=${DEAL_URL:deal-service:8081}
