apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  application.properties: |
    server.port={{ .Values.env.SERVER_PORT }}
    conveyor.url={{ .Values.env.CONVEYOR_URL }}
    spring.datasource.url={{ .Values.env.SPRING_DATASOURCE_URL }}
    spring.datasource.username={{ .Values.env.SPRING_DATASOURCE_USERNAME }}
    spring.datasource.password={{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
    spring.kafka.producer.bootstrap-servers={{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}
