apiVersion: v1
kind: ConfigMap
metadata:
  name: dossier-config
data:
  application.properties: |
    SERVER_PORT={{ .Values.config.serverPort }}
    DEAL_URL={{ .Values.config.dealUrl }}
    SPRING_KAFKA_BOOTSTRAP_SERVERS={{ .Values.config.kafkaBootstrapServers }}
    SPRING_MAIL_HOST={{ .Values.config.mailHost }}
    SPRING_MAIL_USERNAME={{ .Values.config.mailUsername }}
    SPRING_MAIL_PASSWORD={{ .Values.config.mailPassword }}
