apiVersion: apps/v1
kind: Deployment
metadata:
  name: dossier
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dossier
  template:
    metadata:
      labels:
        app: dossier
    spec:
      containers:
        - name: dossier
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: dossier-config
