replicaCount: 2

image:
  repository: ibra26gim/deal
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  SERVER_PORT: 8081
  CONVEYOR_URL: conveyor-service:8080
  SPRING_DATASOURCE_URL: jdbc:postgresql://deal-db:5432/deal
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: root
  KAFKA_BOOTSTRAP_SERVERS: kafka:29092

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 15
    pullPolicy: IfNotPresent
  service:
    port: 5432
  env:
    POSTGRES_DB: deal
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: root

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 10s
    labels:
      release: prometheus
